import React, { useState } from 'react';
import ExchangeCard from '../components/ExchangeCard';
import Svg, { Path } from 'react-native-svg';
import { ScrollView, StyleSheet, Text, View, Pressable, Modal } from 'react-native';
import { Back, Button, Pill } from '../components/UI';
import { colors, common, fonts } from '../theme';
import { money } from '../domain/rules';
import type { DemoState, Exchange } from '../types';
export default function ExchangeProgramScreen({ state, back, initialPiece, request, busy, openExchange }: { state: DemoState; back: () => void; initialPiece?: string; request: (pieceId: string) => Promise<boolean>; busy: boolean; openExchange: (exchange: Exchange) => void }) {
  const [expanded, setExpanded] = useState(false); const [selected, setSelected] = useState(initialPiece || state.eligible[0]?.id || '');
  const requested = state.exchanges.filter(item => item.status === 'Solicitada');
  const completed = state.exchanges.filter(item => item.status === 'Realizada');
  const available = state.eligible.filter(p => !state.exchanges.some(e => e.pieceId === p.id));
  async function send() { if (await request(selected)) setExpanded(false); }
  function expand() { if (!available.some(p => p.id === selected)) setSelected(available[0]?.id || ''); setExpanded(true); }
  return <View style={{ flex: 1 }}><Pressable accessibilityRole="button" accessibilityLabel="Como funciona o Exchange Program" onPress={expand} style={s.header}><View style={s.kicker}><View style={s.dot}><Svg width={18} height={18} viewBox="0 0 24 24"><Path d="M4 7h16m-4-4 4 4-4 4M20 17H4m4-4-4 4 4 4" fill="none" stroke={colors.pink} strokeWidth={1.8} strokeLinecap="round" strokeLinejoin="round" /></Svg></View><Text style={s.kickerText}>EXCHANGE PROGRAM</Text></View><Text style={s.title}>Troque sua peça{'\n'}sem perder valor</Text><Text style={s.subtitle}>Devolva uma peça comprada na Next Chapter e troque por outra, pagando apenas uma taxa administrativa.</Text></Pressable><ScrollView style={{ flex: 1 }} contentContainerStyle={{ padding: 22, gap: 12 }}><Text style={common.heading}>Histórico de trocas</Text><Text style={common.label}>Solicitações de troca ({requested.length})</Text>{requested.length ? requested.map(item => <ExchangeCard key={item.id} exchange={item} onPress={() => openExchange(item)} />) : <Text style={common.text}>Você ainda não solicitou uma troca.</Text>}<Text style={[common.label, { marginTop: 10 }]}>Trocas realizadas ({completed.length})</Text>{completed.length ? completed.map(item => <ExchangeCard key={item.id} exchange={item} onPress={() => openExchange(item)} />) : <Text style={common.text}>Nenhuma troca realizada. Suas solicitações precisam passar pela avaliação da curadoria antes da conclusão.</Text>}</ScrollView><View style={s.controls}><Back onPress={back} /><Button title="Realizar uma nova troca" onPress={expand} style={{ flex: 1 }} /></View>
  <Modal visible={expanded} transparent animationType="fade" onRequestClose={() => setExpanded(false)}><View style={s.overlay}><View style={s.sheet}><ScrollView contentContainerStyle={{ gap: 16 }}><Text accessibilityRole="header" style={common.heading}>Seu próximo capítulo</Text><Text style={[common.text, { lineHeight: 19 }]}>1. Selecione uma peça elegível comprada conosco.{ '\n\n' }2. Envie a solicitação para a curadoria avaliar o estado e a autenticidade.{ '\n\n' }3. Após aprovação, receba uma proposta de crédito e escolha outra bolsa.{ '\n\n' }A taxa administrativa será informada antes da confirmação. Este protótipo simula a solicitação; nenhum valor é cobrado e o crédito não é liberado automaticamente.</Text><Text style={common.label}>Escolha sua peça</Text>{available.length ? available.map(p => <Pill key={p.id} label={`${p.name} · ≈ ${money(p.credit)}`} selected={selected === p.id} onPress={() => setSelected(p.id)} />) : <Text style={common.text}>Todas as suas peças já possuem solicitação de troca.</Text>}<Button title={busy ? 'Solicitando...' : 'Confirmar solicitação de troca'} disabled={busy || !available.some(p => p.id === selected)} onPress={send} /><Button title="Fechar" dark onPress={() => setExpanded(false)} /></ScrollView></View></View></Modal></View>;
}
const s = StyleSheet.create({ header: { backgroundColor: colors.brown, padding: 23, paddingTop: 57, paddingBottom: 25 }, kicker: { flexDirection: 'row', alignItems: 'center', gap: 10 }, dot: { width: 29, height: 29, borderRadius: 15, backgroundColor: colors.olive, alignItems: 'center', justifyContent: 'center' }, kickerText: { fontFamily: fonts.bold, fontSize: 12, color: colors.pink }, title: { fontFamily: fonts.black, fontSize: 25, lineHeight: 29, color: colors.cream, marginTop: 10 }, subtitle: { fontFamily: fonts.regular, fontSize: 13, lineHeight: 16, color: colors.sand, marginTop: 9 }, controls: { padding: 20, flexDirection: 'row', alignItems: 'center', gap: 12 }, overlay: { flex: 1, backgroundColor: '#00000066', justifyContent: 'center', alignItems: 'center', padding: 22 }, sheet: { width: '100%', maxWidth: 370, maxHeight: '90%', backgroundColor: colors.cream, borderRadius: 20, padding: 24 } });