import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Back, Badge, Button, Pill } from '../components/UI';
import { colors, common, fonts } from '../theme';
import { money } from '../domain/rules';
import type { Product } from '../types';
export default function ProductDetailScreen({ product, back, buy, favorite, toggleFavorite, busy }: { product: Product; back: () => void; buy: () => void; favorite: boolean; toggleFavorite: () => void; busy: boolean }) {
  return <View style={{ flex: 1 }}><ScrollView contentContainerStyle={{ flexGrow: 1 }}><View style={s.photo}><Back onPress={back} /><View style={s.badge}><Badge full /></View></View><View style={s.details}><Text style={[common.heading, { fontSize: 24 }]}>{product.brand}</Text><Text style={common.text}>{product.detail}</Text><Text style={s.price}>{money(product.price)}</Text><View style={s.pills}><Pill compact label={`Estado: ${product.condition}`} /><Pill compact label={`Ano: ${product.year}`} /><Pill compact label={`Tamanho: ${product.size}`} /></View><Text style={[common.label, { marginTop: 16 }]}>Sobre a peça</Text><Text style={[common.text, { marginTop: 15, lineHeight: 16 }]}>Cada peça já fez parte da história de alguém. Esta bolsa passou por curadoria e autenticação completas — na Next Chapter, ela ganha uma nova oportunidade de continuar sua jornada.</Text></View></ScrollView><View style={s.footer}><Pressable accessibilityRole="button" accessibilityLabel={favorite ? 'Remover dos favoritos' : 'Adicionar aos favoritos'} accessibilityState={{ selected: favorite, disabled: busy }} disabled={busy} onPress={toggleFavorite} style={[s.favorite, favorite && { backgroundColor: colors.pink }]}>{favorite && <Text style={{ color: colors.brown }}>♥</Text>}</Pressable><Button title="Comprar agora" onPress={buy} style={{ flex: 1 }} /></View></View>;
}
const s = StyleSheet.create({ photo: { backgroundColor: colors.sand, height: 356, padding: 20 }, badge: { position: 'absolute', bottom: 7, left: 16 }, details: { paddingHorizontal: 22, paddingTop: 43, paddingBottom: 30, flex: 1 }, price: { fontFamily: fonts.bold, color: colors.price, fontSize: 22, marginTop: 15 }, pills: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 15 }, footer: { backgroundColor: colors.white, flexDirection: 'row', paddingHorizontal: 22, paddingVertical: 12, gap: 11 }, favorite: { backgroundColor: colors.cream, width: 42, height: 42, borderRadius: 22, alignSelf: 'center', alignItems: 'center', justifyContent: 'center' } });