import React from 'react';
import { ScrollView, Text, View } from 'react-native';
import { Back, Button } from '../components/UI';
import { colors, common } from '../theme';
import { money } from '../domain/rules';
import { dataMode } from '../services/supabase';
import type { DemoState, Product } from '../types';
export default function ProfileScreen({ state, products, back, openProduct }: { state: DemoState; products: Product[]; back: () => void; openProduct: (p: Product) => void }) {
  const favorites = products.filter(p => state.favorites.includes(p.id));
  return <ScrollView contentContainerStyle={common.body}><Back onPress={back} /><Text style={common.heading}>Meu capítulo</Text><Text style={common.text}>Perfil de demonstração · Dados: {dataMode}</Text><View style={{ backgroundColor: colors.brown, borderRadius: 16, padding: 20, gap: 8 }}><Text style={[common.text, { color: colors.cream }]}>Crédito disponível</Text><Text style={[common.heading, { color: colors.pink }]}>{money(state.credit)}</Text></View><Text style={common.label}>Favoritos ({favorites.length})</Text>{favorites.length ? favorites.map(p => <Button key={p.id} title={`${p.brand} · ${p.model}`} onPress={() => openProduct(p)} />) : <Text style={common.text}>Salve uma bolsa pelo botão de favorito no detalhe.</Text>}<Text style={common.label}>Compras simuladas ({state.orders.length})</Text>{state.orders.map(o => <View key={o.id} style={{ gap: 5 }}><Text style={common.label}>{o.productName}</Text><Text style={common.text}>{money(o.total)} · Crédito usado: {money(o.creditUsed)}</Text><Text style={common.text}>Pedido {o.id} · {new Date(o.createdAt).toLocaleDateString('pt-BR')}</Text></View>)}{!state.orders.length && <Text style={common.text}>Você ainda não realizou uma compra.</Text>}<Text style={common.label}>Peças enviadas ({state.sales.length})</Text>{state.sales.map(s => <View key={s.id} style={{ gap: 4 }}><Text style={common.label}>{s.brandModel}</Text><Text style={common.text}>{s.status} · {s.condition} · {s.photos.length} fotos</Text><Text style={common.text}>{money(s.estimate[0])} – {money(s.estimate[1])}</Text></View>)}{!state.sales.length && <Text style={common.text}>Nenhuma peça em curadoria.</Text>}<Text style={common.label}>Trocas ({state.exchanges.length})</Text>{state.exchanges.map(e => <Text key={e.id} style={common.text}>{e.pieceName} · {e.status}</Text>)}{!state.exchanges.length && <Text style={common.text}>Nenhuma troca solicitada.</Text>}</ScrollView>;
}