import React from 'react';
import { ScrollView, StyleSheet, Text, View, Pressable } from 'react-native';
import { Back, Button } from '../components/UI';
import ProductPhoto from '../components/ProductPhoto';
import { colors, common, fonts } from '../theme';
import { money } from '../domain/rules';
import type { DemoState } from '../types';
export default function TradeInScreen({ state, back, useCredit, program }: { state: DemoState; back: () => void; useCredit: () => void; program: (pieceId?: string) => void }) {
  return <ScrollView style={{ backgroundColor: colors.rose }} contentContainerStyle={{ padding: 22, paddingTop: 12, flexGrow: 1 }}><Back onPress={back} /><Text style={common.heading}>Exchange &amp; Trade-in</Text><Text style={[common.text, { marginTop: 5, lineHeight: 15 }]}>Não se adaptou com a sua peça? Não era o que você imaginou? Você pode devolver ela e comprar outra!!! E ainda mais, transforme peças paradas no armário em crédito.</Text><View style={s.wallet}><Text style={[common.text, { color: colors.cream, fontSize: 11 }]}>Seu crédito disponível</Text><Text style={s.credit}>{money(state.credit)}</Text><Button small title="Usar crédito no catálogo" onPress={useCredit} /></View><Text style={[common.label, { marginTop: 13, marginBottom: 10 }]}>Suas peças elegíveis</Text><View style={{ gap: 10 }}>{state.eligible.map(piece => <Pressable key={piece.id} accessibilityRole="button" accessibilityLabel={`Solicitar troca de ${piece.name}`} onPress={() => program(piece.id)} style={s.piece}><ProductPhoto product={piece} style={s.thumbnail} /><View style={{ flex: 1 }}><Text style={common.text}>{piece.name}</Text><Text style={s.pieceCredit}>{state.exchanges.some(e => e.pieceId === piece.id) ? 'Troca solicitada' : `≈ ${money(piece.credit)} em crédito`}</Text></View></Pressable>)}</View><View style={s.program}><Text style={common.label}>🔄 Exchange Program</Text><Text style={[common.text, { fontSize: 12, lineHeight: 14, marginTop: 5 }]}>Devolva uma bolsa comprada conosco e troque por outra peça, pagando apenas uma taxa administrativa.</Text><Button title="Solicitar troca" small dark onPress={() => program()} style={{ marginTop: 3 }} /></View></ScrollView>;
}
const s = StyleSheet.create({ wallet: { backgroundColor: colors.brown, padding: 21, borderRadius: 19, gap: 5, marginTop: 17 }, credit: { fontFamily: fonts.bold, fontSize: 28, color: colors.pink }, piece: { borderRadius: 13, padding: 11, backgroundColor: colors.white, flexDirection: 'row', gap: 12, alignItems: 'center', minHeight: 67 }, thumbnail: { width: 58, height: 58, borderRadius: 8, backgroundColor: colors.white }, pieceCredit: { fontFamily: fonts.regular, fontSize: 10, color: colors.badge, marginTop: 4 }, program: { backgroundColor: colors.cream, borderRadius: 15, borderWidth: 1, borderColor: colors.brown, paddingHorizontal: 21, paddingTop: 20, paddingBottom: 17, marginTop: 11 } });
